#!/bin/bash

outputWidth=80
divider=""
subDivider=""
system_info_file="$HOME/system_info.txt"

for i in $( seq 1 $outputWidth ); do divider+="*" subDivider+="-"; done

main_switch $1

main_switch(){
  case $1 in
    0) exit 1 ;;
    1) serve_system_info_file ;;
    2) system_info ;;
    3) echo 3 ;;
    4) echo 4 ;;
    5) echo 5 ;;
    6) echo 6 ;;
    *) show_menu ;;
  esac
}

show_menu(){
  clear
  printf "\n$divider\n"
  printf "* %-$((outputWidth-4))s *\n" \
  "Wybierz opcje [0 - 6] lub wywolaj skrypt z argumentem" \ \
  "0 - Opuszczenie skryptu" \
  "1 - Zbierz informacje o systemie" \
  "2 - Wyswietl zapisane informacje" \
  "3 - Utworz grupe" \
  "4 - Utworz uzytkownika" \
  "5 - Pobierz i przetworz plik" \
  "6 - Wyszukaj frazy w plikach"
  printf "$divider\n\n"
  read -p "Wybierz opcje: " chosedOption
  main_switch $chosedOption
}

clear(){
  printf "\ec"
}

# if [ $# -eq 0 ] ; then
#   showMenu
# else
#   chosedOption=$1
# fi

# region zad1

serve_system_info_file(){
  if [ -f $system_info_file ] ; then
    rm $system_info_file
    echo "Usunieto istniejacy plik $system_info_file"
  fi
  system_info > $system_info_file
  echo "Utworzono plik $system_info_file"
  echo "Zapisano informacje o systemie"
  sleep 2s
  show_menu
}

system_info(){
  clear
  printf "*** Informacje o systemie ***\n"
  printf "%-21s : %s\n" \
  "Zalogowany uzytkownik" $USER \
  "Katalog domowy" $HOME
  printf "%s\n" \
  "Informacje o pamieci:" \
  "$subDivider" \
  "$(free)" \
  "$subDivider" \
  "Calkowita przestrzen na dysku:" \
  "$subDivider" \
  "$(df)" \
  "$subDivider" \
  "Przestrzen katalogu domowego uzytkownika:" \
  "$(du -sh $HOME)" \
  "$subDivider"
  if [ $EUID == 0 ]; then
    printf "Przestrzen katalogow domowych wszystkich uzytkownikow:"
    printf "\n%s\n" "$(du -shc /home/*)"
    printf "%s$subDivider\n"
  fi
}

# endregion zad1
