#!/bin/bash

arg=$1
system_info_file="$HOME/system_info.txt"
delayTime=2s

outputWidth=80
divider=""
subDivider=""

# on init

for i in $( seq 1 $outputWidth ); do divider+="*" subDivider+="-"; done

# region menu

show_menu(){
  clear
  printf "$divider\n"
  printf "* %-$((outputWidth-4))s *\n" \
  "Wybierz opcje [0 - 6] lub wywolaj skrypt z argumentem" \ \
  "0 - Opuszczenie skryptu" \
  "1 - Zbierz informacje o systemie" \
  "2 - Wyswietl zapisane informacje" \
  "3 - Utworz grupe" \
  "4 - Utworz uzytkownika" \
  "5 - Pobierz i przetworz plik" \
  "6 - Wyszukaj frazy w plikach" \ ""
  printf "$divider\n"
  read -p "Wybierz opcje: " arg
}

clear(){
  printf "\ec"
}

# endregion menu

# region zad1

save_system_info(){
  clear
  if [ -f $system_info_file ] ; then
    rm $system_info_file
    echo "Usunieto istniejacy plik $system_info_file"
  fi
  get_system_info > $system_info_file
  echo "Utworzono plik $system_info_file"
  echo "Zapisano informacje o systemie"
  sleep $delayTime
  show_menu
}

get_system_info(){
  printf "*** Informacje o systemie ***\n"
  printf "%-21s : %s\n" \
  "Zalogowany uzytkownik" $USER \
  "Katalog domowy" $HOME
  printf "%s\n" \
  "Informacje o pamieci:" \
  "$subDivider" \
  "$(free)" \
  "$subDivider" \
  "Calkowita przestrzen na dysku:" \
  "$subDivider" \
  "$(df)" \
  "$subDivider" \
  "Przestrzen katalogu domowego uzytkownika:" \
  "$(du -sh $HOME)" \
  "$subDivider"
  if [ $EUID == 0 ]; then
    printf "Przestrzen katalogow domowych wszystkich uzytkownikow:"
    printf "\n%s\n" "$(du -shc /home/*)"
    printf "%s$subDivider\n"
  fi
}

# endregion zad1

# region zad2

read_system_info(){
  clear
  if [ -f $system_info_file ] ; then
    cat $system_info_file
  else
    echo "Plik ${system_info_file} nie istnieje."
  fi
  sleep $delayTime
  show_menu
}

# endregion zad2

# region mainloop

until [ $arg -eq 0 ]; do
  case $arg in
    1) save_system_info ;;
    2) read_system_info ;;
    # 3)  ;;
    # 4)  ;;
    # 5)  ;;
    # 6)  ;;
    0) exit 1 ;;
    *) show_menu ;;
  esac
done

# endregion mainloop
